# Adding include path as desc in Documentation/kbuild/modules.txt
ccflags-y := -I$(KDIR)/include

obj-m += lib/

incdirs := $(M) $(KDIR)/include/linux $(KDIR)/lib
clean-files := $(foreach dir,$(incdirs),$(wildcard $(dir)/*~))
