# Adding include path as desc in Documentation/kbuild/modules.txt
ccflags-y := -I$(KDIR)/include

# Handle if qmempool is defined in kernel
ifndef CONFIG_QMEMPOOL
       CONFIG_QMEMPOOL=m
endif
obj-$(CONFIG_QMEMPOOL) += qmempool.o

obj-m += qmempool_test.o
obj-m += qmempool_bench.o
obj-m += slab_test.o
