# Adding include path as desc in Documentation/kbuild/modules.txt
ccflags-y := -I$(KDIR)/include

# Handle if qmempool is defined in kernel
ifdef CONFIG_QMEMPOOL
      CONFIG_QMEMPOOL=n
endif

# Local .config settings
include $(KDIR)/.config

obj-$(CONFIG_QMEMPOOL)       += qmempool.o
obj-$(CONFIG_QMEMPOOL_TESTS) += qmempool_test.o
obj-$(CONFIG_QMEMPOOL_TESTS) += qmempool_bench.o

obj-$(CONFIG_SLAB_TESTS) += slab_test.o

# Only compile BULK-API users if local .config enable it
obj-$(CONFIG_SLAB_BULK) += slab_bulk_test01.o
