# Adding include path as desc in Documentation/kbuild/modules.txt
ccflags-y := -I$(KDIR)/include

# Local .config settings
include $(KDIR)/.config

obj-$(CONFIG_BENCH_PAGE) += page_bench01.o
obj-$(CONFIG_BENCH_PAGE) += page_bench02.o
obj-$(CONFIG_BENCH_PAGE) += page_bench03.o

obj-$(CONFIG_BENCH_PAGE) += page_bench05_cross_cpu.o

# Depend on non-upstream kernel patches
obj-$(CONFIG_PAGE_BULK_API) += page_bench04_bulk.o
