# Adding include path as desc in Documentation/kbuild/modules.txt
ccflags-y := -I$(KDIR)/include

obj-m += time_bench.o
obj-m += time_bench_sample.o

obj-m += ring_queue.o
obj-m += ring_queue_test.o

obj-m += alf_queue.o
obj-m += alf_queue_test.o
obj-m += alf_queue_bench.o
obj-m += alf_queue_concurrency_test.o
