# Adding include path as desc in Documentation/kbuild/modules.txt
ccflags-y := -I$(KDIR)/include

# Handle if alf_queue is defined in kernel
ifdef CONFIG_ALF_QUEUE
      CONFIG_ALF_QUEUE=n
endif

# Local .config settings
include $(KDIR)/.config

obj-$(CONFIG_ALF_QUEUE)       += alf_queue.o
obj-$(CONFIG_ALF_QUEUE_TESTS) += alf_queue_test.o
obj-$(CONFIG_ALF_QUEUE_TESTS) += alf_queue_bench.o
obj-$(CONFIG_ALF_QUEUE_TESTS) += alf_queue_concurrency_test.o
obj-$(CONFIG_ALF_QUEUE_TESTS) += alf_queue_disassemble.o
obj-$(CONFIG_ALF_QUEUE_TESTS) += alf_queue_parallel01.o

obj-$(CONFIG_TIME_BENCH)       += time_bench.o
obj-$(CONFIG_TIME_BENCH_TESTS) += time_bench_sample.o
obj-$(CONFIG_TIME_BENCH_TESTS) += time_bench_kmem_cache1.o
obj-$(CONFIG_TIME_BENCH_TESTS) += time_bench_memset.o
obj-$(CONFIG_TIME_BENCH_TESTS) += time_bench_parallel.o

obj-$(CONFIG_RING_QUEUE)       += ring_queue.o
obj-$(CONFIG_RING_QUEUE_TESTS) += ring_queue_test.o

obj-$(CONFIG_SKB_ARRAY_TESTS) += skb_array_test01.o
obj-$(CONFIG_SKB_ARRAY_TESTS) += skb_array_bench01.o
obj-$(CONFIG_SKB_ARRAY_TESTS) += skb_array_parallel01.o

obj-$(CONFIG_BENCH_PAGE_POOL) += bench_page_pool_simple.o
obj-$(CONFIG_BENCH_PAGE_POOL) += bench_page_pool_cross_cpu.o
